// Code generated by "stringer -type=AddressType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownAddress-0]
	_ = x[EVMAddress-1]
	_ = x[BitcoinAddress-2]
	_ = x[SolanaAddress-3]
}

const _AddressType_name = "unknownevmbitcoinsolana"

var _AddressType_index = [...]uint8{0, 7, 10, 17, 23}

func (i AddressType) String() string {
	if i < 0 || i >= AddressType(len(_AddressType_index)-1) {
		return "AddressType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AddressType_name[_AddressType_index[i]:_AddressType_index[i+1]]
}
