// Code generated by "stringer -type=AddressType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownAddress-0]
	_ = x[EVMAddress-1]
	_ = x[BitcoinAddress-2]
	_ = x[SolanaAddress-3]
	_ = x[TronAddress-4]
}

const _AddressType_name = "unknownevmbitcoinsolanatron"

var _AddressType_index = [...]uint8{0, 7, 10, 17, 23, 27}

func (i AddressType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AddressType_index)-1 {
		return "AddressType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AddressType_name[_AddressType_index[idx]:_AddressType_index[idx+1]]
}
